---

- name: template > Template
  template:
    src: "{{ manala_motd_template|ternary(manala_motd_template, 'template/_default.j2') }}"
    dest: "{{ manala_motd_file }}"
  when: manala_motd_template
        or manala_motd_message
